### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by fabrizioschiavi** [esn89/dotfiles#4]
I’m the designer and owner of the rights of PragmataPro
Please remove asap the font files of your repository https://github.com/esn89/dotfiles/tree/master/.fonts
Thanks!

Fabrizio Schiavi
https://www.fsd.it/shop/fonts/pragmatapro/

**Comment by esn89** [comment]
Sorry.

It has been done:
https://github.com/esn89/dotfiles/tree/master/.fonts

**Comment by fabrizioschiavi** [comment]
Thanks for your understanding
